# This is a basic workflow to help you get started with Actions

name: Deploy source read

# Controls when the workflow will run
on:
  # 只在main上push触发部署
  push:
    branches:
      - main
    # 下列文件的变更不触发部署，可以自行添加
    paths-ignore:
      - README.md
      - LICENSE

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # 工作流名称叫做 部署
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 利用action把build好的文件上传到服务器指定目录下路径下
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # 公网 IP 或 域名
          username: ${{ secrets.SSH_USERNAME }} # 登录名
          password: ${{ secrets.SSH_PASSWORD }} # 密码
          port: ${{ secrets.SSH_PORT }} # 端口
          script: |
            cd /usr/local/html/source-read
            git pull
            npm install
            npm run dev
